[dev]
  targetPort = 3002

[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[context.production.environment]
  REACT_APP_ANALYTICS_ENV = "production"
  TWILIO_API_KEYS_ENV = "production"
  NODE_ENV="production"
  REACT_APP_SOCKET_HOST="wss://mercury.with.so:8443"

[context.deploy-preview.environment]
  REACT_APP_ANALYTICS_ENV = "staging"
  TWILIO_API_KEYS_ENV = "staging"
  NODE_ENV="preview"

[context.branch-deploy.environment]
  REACT_APP_ANALYTICS_ENV = "staging"
  TWILIO_API_KEYS_ENV = "staging"
  NODE_ENV="branch-deploy"
