[dev]
  targetPort = 3002

[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[context.production.environment]
  REACT_APP_ANALYTICS_ENV = "production"
  TWILIO_API_KEYS_ENV = "production"
  NODE_ENV="production"
  REACT_APP_SOCKET_HOST="wss://mercury.with.so:8443"
  REACT_APP_API_HOST="https://mercury.with.so:8443"
  REACT_APP_ANALYTICS_ID="c5dca48b9e8589e669570e0d795eb51a"

[context.deploy-preview.environment]
  REACT_APP_ANALYTICS_ENV = "staging"
  TWILIO_API_KEYS_ENV = "staging"
  NODE_ENV="staging"
  REACT_APP_API_HOST="https://test.with.so:8443"
  REACT_APP_ANALYTICS_ID="d44d2fa32ab1fad61038134cdbea9620"

[context.branch-deploy.environment]
  REACT_APP_ANALYTICS_ENV = "staging"
  TWILIO_API_KEYS_ENV = "staging"
  NODE_ENV="staging"
  REACT_APP_API_HOST="https://test.with.so:8443"
  REACT_APP_ANALYTICS_ID="d44d2fa32ab1fad61038134cdbea9620"

